## Project 3:  Immigrants in Georgia, USA

#### Structure / Methodology
1. Import the csv and merge the data files
2. Store merged data file to a database
3. Use flask to export database into a JSON
4. Use JavaScript to load the JSON into the HTML
5. Design the HTML

#### Team Members
+ Mary Jane Rafol
+ Alexis Hernandez
+ Yuanfeng Xu
+ Taib Diallo

### Project 3 Rubric Guide

#### Data and Data Delivery

+ Professional level documentation
+ Dataset have 100 unique records
+ Database is used to house data (SQL, MongoDB, SQLite)
+ Powered by a Python API
+ HTML/CSS
+ JavaSCript

#### Back-end
+ At least one unintroduced JS library
+ Data visualization runs without error
+ A dashboard page with multiple charts that update from the same data

#### Visualizations
+ A minimum of three unique views presented
+ Multiple user-driven interactions (dropdown, filter or zoom feature)
+ Data story is easy to interpret for users of all levels

#### Group Presentation
+ Each member should speak during the presentation
+ Group is well prepared
+ Presentation is relevant to material
+ Audience impact

#### Slide Deck
+ Clean and professional
+ Relevant to material
+ Effectively demonstrates the project
+ Clear and maintains audience interest

#### Step 1: Import the CSV and Merge the Files

In [1]:
# Import the dependencies
import pandas as pd
import sqlite3
from sqlalchemy import create_engine, engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
Base = declarative_base()

In [2]:
# import and read the csv files per GA county
chatam = "Resources/data/ChathamCounty_data.csv"
chatam_df = pd.read_csv(chatam)

cherokee = "Resources/data/CherokeeCounty_data.csv"
cherokee_df = pd.read_csv(cherokee)

clarke = "Resources/data/ClarkeCounty_data.csv"
clarke_df = pd.read_csv(clarke)

clayton = "Resources/data/ClaytonCounty_data.csv"
clayton_df = pd.read_csv(clayton)

cobb = "Resources/data/CobbCounty_data.csv"
cobb_df = pd.read_csv(cobb)

columbia = "Resources/data/ColumbiaCounty_data.csv"
columbia_df = pd.read_csv(columbia)

dekalb = "Resources/data/DeKalbCounty_data.csv"
dekalb_df = pd.read_csv(dekalb)

douglas = "Resources/data/DouglasCounty_data.csv"
douglas_df = pd.read_csv(douglas)

fayette = "Resources/data/FayetteCounty_data.csv"
fayette_df = pd.read_csv(fayette)

forsyth = "Resources/data/ForsythCounty_data.csv"
forsyth_df = pd.read_csv(forsyth)

fulton = "Resources/data/FultonCounty_data.csv"
fulton_df = pd.read_csv(fulton)

gwinnett = "Resources/data/GwinnettCounty_data.csv"
gwinnett_df = pd.read_csv(gwinnett)

hall = "Resources/data/HallCounty_data.csv"
hall_df = pd.read_csv(hall)

henry = "Resources/data/HenryCounty_data.csv"
henry_df = pd.read_csv(henry)

whitfield = "Resources/data/WhitfieldCounty_data.csv"
whitfield_df = pd.read_csv(whitfield)

In [3]:
# Merge data sets per county in one dataframe
ga_data = chatam_df.append([cherokee_df, clarke_df, clayton_df, cobb_df, columbia_df,
                              dekalb_df, douglas_df, fayette_df, forsyth_df, fulton_df,
                              gwinnett_df, hall_df, henry_df, whitfield_df])
ga_data.head()

,County,State,Round County N Imm,Origin,Origin (tooltip),County % by Origin,County N Imm,Round Total Imm Pop,Total Imm Pop
0,"Chatham County, Georgia",Georgia,7900,Americas,Americas,0.000341,7870,23078000,23077986
1,"Chatham County, Georgia",Georgia,6700,Asia,Asia,0.000492,6713,13641700,13641680
2,"Chatham County, Georgia",Georgia,1500,Caribbean,Caribbean,0.000335,1451,4335900,4335884
3,"Chatham County, Georgia",Georgia,4500,Central America,Central America,0.000303,4467,14764000,14763980
4,"Chatham County, Georgia",Georgia,1300,"Central America, excluding Mexico","Central America, excl. Mexico",0.000368,1292,3513400,3513439

In [4]:
# Check the number of records (> 100 unique records)
ga_data.count()

County                 383
State                  383
Round County N Imm     383
Origin                 383
Origin (tooltip)       383
County % by Origin     383
County N Imm           383
Round Total Imm Pop    383
Total Imm Pop          383
dtype: int64

In [5]:
# Clean and rename the columns in preparation for upload to SQL
ga_data_final = ga_data.rename(columns={'Round County N Imm': 'ImmCountRounded',
                                       'Origin (tooltip)': 'OriginTooltip',
                                       'County % by Origin': 'CountyPercentbyOrigin',
                                       'County N Imm': 'ImmCount',
                                       'Round Total Imm Pop': 'TotalImmPopRounded',
                                       'Total Imm Pop': 'TotalImm'})
ga_data_final.head()

,County,State,ImmCountRounded,Origin,OriginTooltip,CountyPercentbyOrigin,ImmCount,TotalImmPopRounded,TotalImm
0,"Chatham County, Georgia",Georgia,7900,Americas,Americas,0.000341,7870,23078000,23077986
1,"Chatham County, Georgia",Georgia,6700,Asia,Asia,0.000492,6713,13641700,13641680
2,"Chatham County, Georgia",Georgia,1500,Caribbean,Caribbean,0.000335,1451,4335900,4335884
3,"Chatham County, Georgia",Georgia,4500,Central America,Central America,0.000303,4467,14764000,14763980
4,"Chatham County, Georgia",Georgia,1300,"Central America, excluding Mexico","Central America, excl. Mexico",0.000368,1292,3513400,3513439

In [6]:
#  Export the consolidated GA immigrant data
ga_data_final.to_csv("Resources/output/ga_data.csv")

In [7]:
ga_data_final=ga_data_final.reset_index

In [8]:
# ga_data_final.to_json(r'Resources/output/ga_data.json')

#### Step 2: Store Merged Data File to SQLite Database

In [9]:
# Create a GA immigrant path using SQLite
sql_data = 'ga.sqlite'

# Create a database connection
conn = sq.connect(sql_data)

# Create a table in SQLite
ga_data_final.to_sql('ga_immigrants', conn, if_exists='replace', index=False) 

# Read the SQL
pd.read_sql('select * from ga_immigrants', conn)

NameError: name 'sq' is not defined